Repository PIP-Technical-Team/pipapi, pull requests merged in 2022-03, with the labels that each got.

#213 Add povline NULL option for cp_key_indicators()
  R/ui_functions.R
  man/ui_cp_key_indicators.Rd
  tests/testthat/test-ui_functions.R
  tests/testthat/test-utils-plumber.R
Labels: Priority: 1-Blocker, Type: 1-Bug

#210 Fix dist stats when fill_gaps = TRUE
  NEWS.md
  R/fg_pip.R
  R/pip.R
  R/utils.R
  tests/testthat/test-pip-local.R
  tests/testthat/test-pip.R
Labels: Priority: 2-High, Type: 1-Bug

#197 Add reporting_level to ui_cp_poverty_charts()
  R/ui_functions.R
  tests/testthat/test-plumber-ui.R
  tests/testthat/test-ui_functions.R
Labels: Priority: 3-Medium

#216 Fix latest data version
  NEWS.md
  R/create_lkups.R
  data-raw/data.R
  inst/plumber/v1/endpoints.R
  tests/testthat/test-fg_pip-local.R
  tests/testthat/test-get_aux_table.R
  tests/testthat/test-pip-local.R
  tests/testthat/test-pip.R
  tests/testthat/test-ui_functions.R
  tests/testthat/test-utils-plumber.R
Labels: Priority: 2-High, Type: 2-Enhancement

#217 Add country and region name to /pip response
  NEWS.md
  R/create_lkups.R
  data/empty_response.rda
  data/empty_response_cp_poverty.rda
  data/reporting_level_list.rda
Labels: Priority: 2-High, Type: 2-Enhancement

#205 Fix aggregation handling of URY/ARG
  R/add_agg_stats.R
  R/create_lkups.R
Labels: Priority: 2-High

#219 Finalize pip grp
  NEWS.md
  R/create_lkups.R
  R/pip.R
  R/pip_grp.R
  R/ui_functions.R
  R/utils.R
  data-raw/data.R
  data/empty_response_grp.rda
  inst/plumber/v1/openapi.yaml
  man/empty_response.Rd
  man/pip_grp.Rd
  tests/testthat/test-pip-local.R
  tests/testthat/test-pip.R
  tests/testthat/test-pip_grp.R
  tests/testthat/test-plumber.R
Labels: Priority: 2-High, Type: 1-Bug, Type: 2-Enhancement

#225 Fix aggregation
  R/fg_pip.R
  R/pip.R
  data/empty_response.rda
  data/empty_response_cp_poverty.rda
  data/empty_response_grp.rda
  data/reporting_level_list.rda
  man/fg_assign_nas_values_to_dup_cols.Rd
  man/fg_remove_duplicates.Rd
  man/fg_standardize_cache_id.Rd
  tests/testthat/test-pip-local.R
  tests/testthat/test-ui_functions.R
Labels: Priority: 1-Blocker, Type: 1-Bug

#232 Add guidelines and templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: Priority: 3-Medium, Type: 2-Enhancement

#239 Add improved error formatting
  R/utils-plumber.R
  R/utils.R
  R/zzz.R
  inst/plumber/v1/endpoints.R
  man/clear_cache.Rd
  tests/testthat/test-utils-plumber.R
Labels: Priority: 2-High, Type: 2-Enhancement

#244 Fix issue #236
  NAMESPACE
  R/create_lkups.R
  R/pip.R
  R/pip_grp.R
  R/utils-plumber.R
  inst/plumber/v1/endpoints.R
  man/extract_data_dirs.Rd
  man/get_vintage_pattern_regex.Rd
  man/id_valid_dirs.Rd
  man/sort_versions.Rd
  tests/testthat/test-plumber.R
  tests/testthat/test-utils-plumber.R
Labels: Priority: 2-High, Type: 1-Bug
